### ISSUE TITLE
Issue with MC Kickass v1.0.0 with Quasar

### ISSUE THREAD

**Issue by Airbox79** [mancuniancol/script.quasar.kickass-mc#1]
Bug Report:
Example, you choose a TV episode within Kodi (library integrated = not tested from within Quasar) and get a choose stream dialog up (so far so good), but when you choose one of the files to stream, Quasar starts to buffer / download (stream) another file than the chosen one (the file size is incorrect), so you actually have stop the stream, and choose again in blindness to get the stream you actually want to look at. I have no idea if this is a Quasar or a provider problem when it comes to sorting and getting the right input from the dialog. Maybe both the Quasar team and MC need to check on this? 

Versions that this issue has been seen:
 MC Kickass for Pulsar v3.0.11 & Pulsar v0.7.1 (i9)
 MC Kickass for Quasar v1.0.0 & Quasar v0.9.1
 MC Kickass for Quasar v1.0.0 & Quasar v0.9.4

Thanks!

Best regards
 AirBox

**Comment by mancuniancol** [comment]
Sometimes, the information from the page is not the same of the torrent. But, if you have a specific case where in the webpage is correct and the provider not. Please let know and share your kodi log in debug mode.

**Comment by mancuniancol** [comment]
I didn't get any feedback from you.  Then, I will close this issue

**Comment by Airbox79** [comment]
Hi Mancuniancol!

Your upgrade to v1.0.1 and v1.1.0 solved this issue!

Thanks! =)

Best regards
AirBox
