### ISSUE TITLE
No links found for kickass provider

### ISSUE THREAD

**Issue by ekeloglu** [mancuniancol/script.quasar.kickass-mc#2]
Hello! First of all, i want to thank you for your great support to the community. I am using quasar v0.9.9 and kickass provider v1.1. I can watch movies or tv shows from kickass viewer with quasar. i can search and watch movies from quasar with eztvi yify or rarbg providers. But i have no luck with kickass provider. I also tried kickass provider with pulsar many times but no luck. I always get "no links found" or "Error 500" after some time.

My system is rasp2 b model and openelec v6.0.1
Here is some log from kodi to see whats happening.

2016-02-08 20:58:01  INFO  linkssearch      Resolving torrent files...
22:58:01 3929.234863 T:1322251328  NOTICE: Thread LanguageInvoker start, auto delete: false
22:58:01 3929.451416 T:1322251328  NOTICE: -->Python Interpreter Initialized<--
22:58:02 3930.724365 T:1322251328  NOTICE: [script.quasar.kickass-mc] http://kat.cr/usearch/the%20martian%202015/?field=seeders&sorder=desc
22:58:04 3932.033447 T:1322251328  NOTICE: [script.quasar.kickass-mc] Accepted Keywords: ['HDTV', '720p', '1080p']
22:58:04 3932.033936 T:1322251328  NOTICE: [script.quasar.kickass-mc] Blocked Keywords: ['3D', 'CAM', 'TeleSync', '?TS?', 'Trailer']
22:58:04 3932.034424 T:1322251328  NOTICE: [script.quasar.kickass-mc] min Size: 0.0 GB
22:58:04 3932.034912 T:1322251328  NOTICE: [script.quasar.kickass-mc] max Size: MAX
22:58:06 3934.253662 T:1480488000  NOTICE: [plugin.video.quasar] 2016-02-08 20:58:06  INFO  AddonSearcher script.quasar.kickass-mc  Provider script.quasar.kickass-mc was too slow. Ignored.
22:58:06 3934.283447 T:1480488000  NOTICE: [plugin.video.quasar] 2016-02-08 20:58:06  INFO  linkssearch      Received 0 links.
22:58:06 3934.622559 T:1480488000  NOTICE: [plugin.video.quasar] [GIN] 2016/02/08 - 20:58:06 |[97;42m 200 [0m|   5.84679683s | 127.0.0.1 |[97;44m  [0m GET     /movie/tt3659388/links
22:58:06 3934.625488 T:1968033792   ERROR: PlayMedia could not play media: plugin://plugin.video.quasar/movie/tt3659388/links
22:58:10 3938.790771 T:1322251328 WARNING: [script.quasar.kickass-mc] The Martian 2015 Hdrip Xvid Etrg ***Blocked File by Keyword***
22:58:10 3938.804688 T:1322251328 WARNING: [script.quasar.kickass-mc] The Martian 2015 French Dvdrip Xvid Ac3 Funkky ***Blocked File by Keyword***
22:58:10 3938.885498 T:1322251328 WARNING: [script.quasar.kickass-mc] The Martian 2015 Webrip Avc Xvid ***Blocked File by Keyword***
22:58:10 3938.912109 T:1322251328 WARNING: [script.quasar.kickass-mc] The Martian 2015 Hd Ts Xvid Ac3 Hq Hive Cm8 ***Blocked File by Keyword***
22:58:10 3938.964844 T:1322251328  NOTICE: [script.quasar.kickass-mc] >>>>>>10 torrents sent to Quasar<<<<<<<
22:58:11 3939.023438 T:1322251328  NOTICE: [script.quasar.kickass-mc] <addinfourl at 1459172616 whose fp = <socket._fileobject object at 0x227cfb0>>
22:58:11 3939.027100 T:1480488000  NOTICE: [plugin.video.quasar] [GIN] 2016/02/08 - 20:58:11 |[97;42m 200 [0m|      16.667Âµs | 192.168.1.61 |[97;46m  [0m POST    /callbacks/1917614833
22:58:25 3953.084473 T:1313862720  NOTICE: Thread BackgroundLoader start, auto delete: false
22:58:25 3953.520020 T:1313862720  NOTICE: Thread LanguageInvoker start, auto delete: false
22:58:25 3953.726807 T:1313862720  NOTICE: -->Python Interpreter Initialized<--
22:58:26 3954.270020 T:1313862720  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/
22:58:26 3954.343750 T:1341027392  NOTICE: Thread BackgroundLoader start, auto delete: false
22:58:26 3954.565674 T:1480488000  NOTICE: [plugin.video.quasar] [GIN] 2016/02/08 - 20:58:26 |[97;42m 200 [0m|     750.573Âµs | 127.0.0.1 |[97;44m  [0m GET     /
22:58:31 3959.361816 T:1366291520  NOTICE: Thread BackgroundLoader start, auto delete: false
22:58:36 3964.551025 T:1366291520  NOTICE: Previous line repeats 1 times.

**Comment by mancuniancol** [comment]
The provider is being time out by Quasar. You need to increase that parameter or reduce the number of providers. If it is only one. The only solution is increase to 30s or more. 

[code]Provider script.quasar.kickass-mc was too slow. Ignored.[/code]

**Comment by mancuniancol** [comment]
I have not feedback from you, I will close this issue

**Comment by ekeloglu** [comment]
Hello again and sorry for late response.

Lile you say, i changed timeout seconds to 35 and problem is solved.

Thanks for the reply.

**Comment by mancuniancol** [comment]
Cool
