### ISSUE TITLE
No links found

### ISSUE THREAD

**Issue by nman999** [mancuniancol/script.quasar.kickass-mc#6]
Hello,
Im using 3 provider plugins (Torrentz,EZTV,Kickass) which I know would give me results for the desired media, but its giving me a "No links found" message (after upgrading to 1.2.2 (latest) versions). Please tell me exactly what I should send to you (log) for you to help me. Could this be a Quasar issue?
thanks a lot,

**Comment by mancuniancol** [comment]
What is it your time out settings in Quasar? Yes, your log will help a lot

**Comment by nman999** [comment]
There is an option in Quasar to set a ¨Custom Provider Timeout", which I havent set. Looking at the log, the provider seems to be sending the links to Quasar, yet, I get the "no links found" message. As soon as I learn to efficiently send a log, I will do that,
thanks,

**Comment by mancuniancol** [comment]
Try to increase to 20 or 30s. Even more

**Comment by nman999** [comment]
I progressively increased to 45 seconds, and quasar is finally showing me the links. I need to ask, how is it possible it takes so long to carry out this search in EZTV, how can an API be so slow?
thanks a lot, 45 seconds is ok for me. Does the provider have anything to do, does the fact that Im running this on a first generation RPi have anything to do with it?
thanks,

**Comment by mancuniancol** [comment]
Your system usually can only handle one provider at the time with the default values. If you leave one it could work.

**Comment by campsiyas** [comment]
just put timeout of 50 sec and then clear cahe, it works
