### ISSUE TITLE
Global name "filtering" is not defined

### ISSUE THREAD

**Issue by Loewkie** [mancuniancol/script.quasar.kickass-mc#7]
[Log](http://paste.osmc.io/efudebaroy).

Any idea what can cause this. Currently all providers seem to be failing due to this error.

**Comment by mancuniancol** [comment]
Which version are you using?

**Comment by Loewkie** [comment]
I'm using the armv7 of quasar with version 0.9.34 on RPi 2

**Comment by Loewkie** [comment]
PS I'm using the latest version of your providers (have installed them straight from here today.

**Comment by mancuniancol** [comment]
That is my point. It seems that you are using version 1.4.0.  Please, use any version 1.3

Version 1.4 needs to Crack Quasar to work.

**Comment by Loewkie** [comment]
I'll try this and let you know how it went.

**Comment by mancuniancol** [comment]
It is better that you install the providers from repo. Or using the zip of the release. https://forums.tvaddons.ag/addon-releases/31572-pulsar-providers-unofficial-pulsar-repo.html

I will close this issue
